esphome:
  name: tesla-2bus-opener
  friendly_name: Tesla 2BUS Opener
  on_boot:
    priority: -200  # Runs early
    then:
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2
      - switch.turn_off: relay_3
      - switch.turn_off: relay_4

esp8266:
  board: d1_mini
  restore_from_flash : true
  early_pin_init: false



# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YourEncryptionKey"

ota:
  - platform: esphome
    password: "YourOTAPassword"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tesla-2Bus-Opener"
    password: "ChooseAPPassword"



switch:
  - platform: gpio
    pin: D1 
    name: "Sluchátko"
    id: relay_1
    inverted: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    pin: D7  
    name: "Tlačítko 1"
    id: relay_2
    inverted: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    pin: D6  
    name: "Tlačítko zámek"
    id: relay_3
    inverted: true
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    pin: D5
    name: "Relay 4"
    id: relay_4
    inverted: true
    restore_mode: RESTORE_DEFAULT_OFF
button:
  - platform: restart
    name: "Restartovat"
